apiVersion: grafana.integreatly.org/v1beta1
kind: Grafana
metadata:
  name: main
  namespace: grafana
  labels:
    dashboards: "main"   # used by instanceSelector below
spec:
  config:
    security:
      admin_user: admin
      admin_password: admin123   # change me
  ingress:
    #metadata:
    #  annotations:
    #    cert-manager.io/cluster-issuer: "letsencrypt-cloudflare"
    spec:
      ingressClassName: contour
      tls:
      - hosts:
        - grafana.vcf.vstackops.com
        secretName: grafana-tls-secret
      rules:
        - host: grafana.vcf.vstackops.com
          http:
            paths:
              - path: /
                pathType: Prefix
                backend:
                  service:
                    name: main-service
                    port:
                      number: 3000